---

exclude:
    - '^(.*)[\/\\\\]project[\/\\\\]{{ label }}[\/\\\\]templates[\/\\\\](.*)$'

ignore:
    - '^(.*)[.]pyc$'
    - '^(.*)[.]pyo$'
    - '^(.*)__pycache__(.*)$'
    - '^(.*)[\/\\\\][.]git(.*)$'

variables:
    -   name: label
        prompt: "App Label"
        case: "lower"
        default: "{{ dest_label }}"

    -   name: name
        prompt: "App Name"
        default: "{{ dest_tail|title|catif(' Application') }}"

    -   name: class_name
        prompt: "App Class Name"
        validate: "^[a-zA-Z0-9]+$"
        default: "{{ dest_tail|pyid(case='title')|catif('App') }}"

    -   name: description
        prompt: "App Description"
        default: "{{ class_name }} Does Amazing Things!"

    -   name: creator
        prompt: "Creator Name"
        default: "John Doe"

    -   name: creator_email
        prompt: "Creator Email"
        default: "john.doe@example.com"

    -   name: url
        prompt: "Project URL"
        default: "https://github.com/johndoe/myapp/"

    -   name: license
        prompt: "License"
        default: "unlicensed"
